name: ai_food
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  #Cubit
  flutter_bloc: ^9.0.0

  #DI
  get_it: ^8.0.3

  #Service
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  equatable: ^2.0.7

  #Qr Scanner
  mobile_scanner: ^6.0.5
  qr_scanner_overlay: ^0.0.2

  #Envied
  envied: ^1.1.0

  #Gemini
  google_generative_ai: ^0.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^7.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  envied_generator: ^1.1.0

flutter:
  uses-material-design: true

